language: c++
python:
- '3.4'
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake unzip libmysqlcppconn-dev:i386
  - chmod +x install-dependencies.sh
install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - ./install-dependencies.sh
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
- cmake extension/build -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
- make -C /
