language: c++
python:
- '3.4'
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install cmake unzip libmysqlcppconn-dev:i386 libmysqlclient-dev:i386
  - chmod +x install-dependencies.sh
install: 
  - sudo apt-get install -qq g++-5
  - sudo apt-get install gcc-5-multilib g++-5-multilib
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - ./install-dependencies.sh
script:
- sed -i "s|^SET(POCO_HOME.*|SET(POCO_HOME \"$PWD\/poco\/\")|" extension/build/CMakeLists.txt
- sed -i "s|^SET(MYSQL_HOME.*|SET(MYSQL_HOME \"$PWD\/mysql\/\")|" extension/build/CMakeLists.txt
- sed -i "s|^SET(MYSQL64_HOME.*|SET(MYSQL64_HOME \"$PWD\/mysql\/\")|" extension/build/CMakeLists.txt
- cd extension/build
- cmake . -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
- make
