language: c++
python:
- '3.4'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake unzip libmysqlcppconn-dev:i386
install: ./install-dependencies.sh
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
- cmake extension/build -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
- make -C /
